stages:
  - build-staging
  - build-prod


### build-staging
build-backend-api-staging:
  stage: build-staging
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend/go"
      --dockerfile "${CI_PROJECT_DIR}/backend/go/Dockerfile-api"
      --destination "${CI_REGISTRY_IMAGE}/backend-api/staging:${CI_PIPELINE_IID}"

build-backend-scheduler-staging:
  stage: build-staging
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend/go"
      --dockerfile "${CI_PROJECT_DIR}/backend/go/Dockerfile-scheduler"
      --destination "${CI_REGISTRY_IMAGE}/backend-scheduler/staging:${CI_PIPELINE_IID}"

build-backend-transform-staging:
  stage: build-staging
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend/go"
      --dockerfile "${CI_PROJECT_DIR}/backend/go/Dockerfile-transform"
      --destination "${CI_REGISTRY_IMAGE}/backend-transform/staging:${CI_PIPELINE_IID}"


### build-prod
build-backend-api-prod:
  stage: build-prod
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/backend/go/Dockerfile-api"
      --destination "${CI_REGISTRY_IMAGE}/backend-api/prod:${CI_PIPELINE_IID}"
  only:
    variables:
      - $env == "prod"

build-backend-scheduler-prod:
  stage: build-prod
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile-scheduler"
      --destination "${CI_REGISTRY_IMAGE}/backend-scheduler/prod:${CI_PIPELINE_IID}"
  only:
    variables:
      - $env == "prod"

build-backend-transform-prod:
  stage: build-prod
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile-transform"
      --destination "${CI_REGISTRY_IMAGE}/backend-transform/prod:${CI_PIPELINE_IID}"
  only:
    variables:
      - $env == "prod"
