stages:
  - build-staging

build-backend-api-staging:
  stage: build-staging
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend/go"
      --dockerfile "${CI_PROJECT_DIR}/backend/go/Dockerfile-api"
      --destination "${CI_REGISTRY_IMAGE}/backend/go/api/staging:${CI_PIPELINE_IID}"

build-backend-scheduler-staging:
  stage: build-staging
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend/go"
      --dockerfile "${CI_PROJECT_DIR}/backend/go/Dockerfile-scheduler"
      --destination "${CI_REGISTRY_IMAGE}/backend/go/scheduler/staging:${CI_PIPELINE_IID}"

build-backend-transform-staging:
  stage: build-staging
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend/go"
      --dockerfile "${CI_PROJECT_DIR}/backend/go/Dockerfile-transform"
      --destination "${CI_REGISTRY_IMAGE}/backend/go/transform/staging:${CI_PIPELINE_IID}"
