version: "3.9"

services:
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2021-03-01T04-20-55Z
    command: server /data
    environment:
      MINIO_ACCESS_KEY: MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: MINIO_SECRET_KEY
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    volumes:
      - minio-data:/data
    restart: unless-stopped

volumes:
  minio-data: