{{ if .Values.ingress.enabled}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.application.name }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.ip }}
    networking.gke.io/managed-certificates: {{ .Values.ingress.host }}-tls
    ingressClassName: "gce"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port }}

---

apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Values.ingress.host }}-tls
spec:
  domains:
    - {{ .Values.ingress.host }}

{{ end }}
