stages:
  - build-staging
  - trigger-deploy-staging
  - build-prod
  - deliver-version-prod


build-staging:
  stage: build-staging
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/game/staging:${CI_PIPELINE_IID}"
  environment:
    name: staging
    url: http://staging.game.k8s.atpstealer.com

trigger-deploy-staging:
  stage: trigger-deploy-staging
  image: curlimages/curl
  script:
    - |
      curl -X PUT -H "PRIVATE-TOKEN: $K8S_DEPLOY_HELM_FULL_ACCESS_TOKEN" \
        -H "Content-Type: application/json" \
        -d '{"value": "'${CI_PIPELINE_IID}'", "protected": false}' \
         "https://gitlab.gl.atpstealer.com/api/v4/projects/4/variables/FRONTEND_STAGING_VERSION"
    -  curl -X POST -F token=$K8S_DEPLOY_HELM_TRIGGER_TOKEN -F ref=main
      -F "variables[RUN_JOB]=frontend"
      https://gitlab.gl.atpstealer.com/api/v4/projects/4/trigger/pipeline
  environment:
    name: staging
    url: http://staging.game.k8s.atpstealer.com

build-prod:
  stage: build-prod
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - mv src/config-prod.ts.tmp src/config.ts
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/game/prod:${CI_PIPELINE_IID}"
  only:
    variables:
      - $env == "prod"
  environment:
    name: prod
    url: https://game.k8s.atpstealer.com

deliver-version-prod:
  stage: deliver-version-prod
  image: curlimages/curl
  script:
    - |
      curl -X PUT -H "PRIVATE-TOKEN: $K8S_DEPLOY_HELM_FULL_ACCESS_TOKEN" \
        -H "Content-Type: application/json" \
        -d '{"value": "'${CI_PIPELINE_IID}'", "protected": false}' \
         "https://gitlab.gl.atpstealer.com/api/v4/projects/4/variables/FRONTEND_PROD_VERSION"
    - curl -X POST -F token=$K8S_DEPLOY_HELM_TRIGGER_TOKEN -F ref=main
      -F "variables[env]=prod"
      https://gitlab.gl.atpstealer.com/api/v4/projects/4/trigger/pipeline

  only:
    variables:
      - $env == "prod"
  environment:
    name: prod
    url: https://game.k8s.atpstealer.com
