auth:
  enabled: true
  existingSecret: mongodb-secrets
architecture: replicaset
replicaCount: 2
externalAccess:
  enabled: true
  service:
    type: LoadBalancer
    externalTrafficPolicy: Cluster
    loadBalancerIPs:
      - 142.132.173.68
      - 88.99.190.155
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "256Mi"
