auth:
  enabled: true
  existingSecret: mongodb-secrets
architecture: replicaset
replicaCount: 2
externalAccess:
  enabled: true
  service:
    type: LoadBalancer
    loadBalancerIPs:
      - 138.201.244.149
      - 49.13.217.89
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "256Mi"
