apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-admin
  namespace: game
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: gitlab

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-managedcerts-editor
  namespace: game
rules:
  - apiGroups: [ "networking.gke.io" ]
    resources: [ "managedcertificates" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-managedcerts-editor
  namespace: game
roleRef:
  kind: Role
  name: gitlab-managedcerts-editor
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: default
    namespace: gitlab