apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ippool
  namespace: metallb-system
spec:
  addresses:
    - 142.132.173.68/32 # gitlab
    - 37.27.216.117/32 # ingress
    - 138.201.244.149/32 # mongo 1
    - 49.13.217.89/32 # mongo 2
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: external
  namespace: metallb-system
spec:
  ipAddressPools:
    - ippool



