apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ippool
  namespace: metallb-system
spec:
  addresses:
    - 128.140.8.77/32 # gitlab
    - 188.245.158.57/32 # ingress
    - 142.132.173.68/32 # mongo 1
    - 88.99.190.155/32 # mongo 2
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: external
  namespace: metallb-system
spec:
  ipAddressPools:
    - ippool



