apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}
spec:
  selector:
    app: {{ .Values.application.name }}
  ports:
    - name: mysql
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.application.name }}
  ports:
    - name: mysql
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
  loadBalancerIP: 35.241.242.215