// This file is auto-generated by @hey-api/openapi-ts

export const controllers_JSONResultSchema = {
  type: 'object',
  properties: {
    code: {
      type: 'integer'
    },
    data: {},
    text: {
      type: 'string'
    },
    values: {}
  }
} as const

export const models_BuildingTypeSchema = {
  type: 'object',
  properties: {
    buildTime: {
      $ref: '#/definitions/time.Duration'
    },
    buildingGroup: {
      type: 'string'
    },
    buildingSubGroup: {
      type: 'string'
    },
    capacity: {
      type: 'number'
    },
    cost: {
      type: 'number'
    },
    description: {
      type: 'string'
    },
    id: {
      type: 'integer'
    },
    requirements: {
      type: 'string'
    },
    title: {
      type: 'string'
    },
    workers: {
      type: 'integer'
    }
  }
} as const

export const models_ConstructBuildingPayloadSchema = {
  type: 'object',
  properties: {
    square: {
      type: 'integer'
    },
    typeId: {
      type: 'integer'
    },
    x: {
      type: 'integer'
    },
    y: {
      type: 'integer'
    }
  }
} as const

export const time_DurationSchema = {
  type: 'integer',
  enum: [
    -9223372036854776000, 9223372036854776000, 1, 1000, 1000000, 1000000000, 60000000000,
    3600000000000
  ],
  'x-enum-varnames': [
    'minDuration',
    'maxDuration',
    'Nanosecond',
    'Microsecond',
    'Millisecond',
    'Second',
    'Minute',
    'Hour'
  ]
} as const
