// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch'
import type {
  PostApiV2BuildingConstructData,
  PostApiV2BuildingConstructError,
  PostApiV2BuildingConstructResponse,
  GetApiV2BuildingTypesError,
  GetApiV2BuildingTypesResponse,
  GetSettingsError,
  GetSettingsResponse
} from './types.gen'

export const client = createClient(createConfig({
  baseUrl: `${import.meta.env.VITE_API}`,
  credentials: 'include'
}))

/**
 * Construct a new building
 * Endpoint for constructing a new building given the payload details.
 */
export const postApiV2BuildingConstruct = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV2BuildingConstructData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    PostApiV2BuildingConstructResponse,
    PostApiV2BuildingConstructError,
    ThrowOnError
  >({
    ...options,
    url: '/building/construct'
  })
}

/**
 * Get all building types
 * Return all available building types from the database
 */
export const getApiV2BuildingTypes = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetApiV2BuildingTypesResponse,
    GetApiV2BuildingTypesError,
    ThrowOnError
  >({
    ...options,
    url: '/building/types'
  })
}

/**
 * Get General Game Settings
 * Get application settings
 */
export const getSettings = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<GetSettingsResponse, GetSettingsError, ThrowOnError>({
    ...options,
    url: '/settings'
  })
}
