// This file is auto-generated by @hey-api/openapi-ts

export interface controllers_JSONResult {
  code?: number;
  data?: unknown;
  text?: string;
  values?: unknown;
}

export interface models_BuildingType {
  buildTime?: time_Duration;
  buildingGroup?: string;
  buildingSubGroup?: string;
  capacity?: number;
  cost?: number;
  description?: string;
  id?: number;
  requirements?: string;
  title?: string;
  workers?: number;
}

export interface models_ConstructBuildingPayload {
  square?: number;
  typeId?: number;
  x?: number;
  y?: number;
}

export enum time_Duration {
  minDuration = -9223372036854776000,
  maxDuration = 9223372036854776000,
  Nanosecond = 1,
  Microsecond = 1000,
  Millisecond = 1000000,
  Second = 1000000000,
  Minute = 60000000000,
  Hour = 3600000000000
}

export interface PostApiV2BuildingConstructData {
  /**
   * Building construction payload
   */
  body: models_ConstructBuildingPayload;
}

export type PostApiV2BuildingConstructResponse = controllers_JSONResult & {
  values?: models_ConstructBuildingPayload;
}

export type PostApiV2BuildingConstructError = unknown

export type GetApiV2BuildingTypesResponse = controllers_JSONResult & {
  data?: models_BuildingType[];
}

export type GetApiV2BuildingTypesError = controllers_JSONResult

export type GetSettingsResponse = controllers_JSONResult

export type GetSettingsError = unknown
