stages:
  - staging
  - infra
  - prod

default:
  before_script:
    - mkdir .kube
    - echo $KUBE_CONFIG_FILE_BASE64 | base64 -d > .kube/config

backend-staging:
  stage: staging
  image: alpine/helm
  script:
    - helm upgrade --install backend-staging -n game
      --set-string application.image.version=$BACKEND_STAGING_VERSION
      -f ./application/backend-staging-values.yaml
      --history-max 2
      ./application

frontend-staging:
  stage: staging
  image: alpine/helm
  script:
    - helm upgrade --install frontend-staging -n game
      --set-string application.image.version=$FRONTEND_STAGING_VERSION
      -f ./application/frontend-staging-values.yaml
      --history-max 2
      ./application

frontend-vue-staging:
  stage: staging
  image: alpine/helm
  script:
    - helm upgrade --install frontend-vue-staging -n game
      --set-string application.image.version=$FRONTEND_VUE_STAGING_VERSION
      -f ./application/frontend-vue-staging-values.yaml
      --history-max 2
      ./application

scheduler-staging:
  stage: staging
  image: alpine/helm
  script:
    - helm upgrade --install scheduler-staging -n game
      --set-string cronjob.image.version=$SCHEDULER_STAGING_VERSION
      -f ./scheduler/scheduler-staging-values.yaml
      --history-max 2
      ./scheduler

transform-staging:
  stage: staging
  image: alpine/helm
  script:
    - helm upgrade --install transform-staging -n game
      --set-string cronjob.image.version=$TRANSFORM_STAGING_VERSION
      -f ./scheduler/transform-staging-values.yaml
      --history-max 2
      ./scheduler

mysql:
  stage: infra
  image: alpine/helm
  script:
    - helm upgrade --install mysql -n game
      --set MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      --history-max 2
      ./mysql

minio:
  stage: infra
  image: alpine/helm
  script:
    - helm upgrade --install minio -n game
      --history-max 2
      --set MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY
      --set MINIO_SECRET_KEY=$MINIO_SECRET_KEY
      ./minio

backend-prod:
  stage: prod
  image: alpine/helm
  script:
    - helm upgrade --install backend-prod -n game
      --set-string application.image.version=$BACKEND_PROD_VERSION
      -f ./application/backend-prod-values.yaml
      --history-max 2
      ./application
  only:
    variables:
      - $env == "prod"

frontend-vue-prod:
  stage: prod
  image: alpine/helm
  script:
    - helm upgrade --install frontend-vue-prod -n game
      --set-string application.image.version=$FRONTEND_VUE_PROD_VERSION
      -f ./application/frontend-vue-prod-values.yaml
      --history-max 2
      ./application
  only:
    variables:
      - $env == "prod"

scheduler-prod:
  stage: prod
  image: alpine/helm
  script:
    - helm upgrade --install scheduler-prod -n game
      --set-string cronjob.image.version=$SCHEDULER_PROD_VERSION
      -f ./scheduler/scheduler-prod-values.yaml
      --history-max 2
      ./scheduler
  only:
    variables:
      - $env == "prod"

transform-prod:
  stage: prod
  image: alpine/helm
  script:
    - helm upgrade --install transform-prod -n game
      --set-string cronjob.image.version=$TRANSFORM_PROD_VERSION
      -f ./scheduler/transform-prod-values.yaml
      --history-max 2
      ./scheduler
  only:
    variables:
      - $env == "prod"
