replicaCount: 1

application:
  name: backend-prod
  image:
    name: registry.gl.atpstealer.com/mav/backend/game/prod
    version: 1
  imagePullSecrets: registry-backend-secrets

service:
  name: backend-prod-srv
  port: 8000

ingress:
  enabled: true
  name: backend-prod-ing
  host: api.game.k8s.atpstealer.com
  tls: true

env:
  - name: DB_DATABASE
    secretKeyRef:
      name: app
      key: DB_DATABASE_PROD
  - name: DB_HOST
    secretKeyRef:
      name: app
      key: DB_HOST
  - name: DB_PASSWORD
    secretKeyRef:
      name: app
      key: DB_PASSWORD
  - name: DB_PORT
    secretKeyRef:
      name: app
      key: DB_PORT
  - name: DB_USER
    secretKeyRef:
      name: app
      key: DB_USER
  - name: GOOGLE_API
    secretKeyRef:
      name: app
      key: GOOGLE_API
  - name: GOOGLE_SHEET_ID
    secretKeyRef:
      name: app
      key: GOOGLE_SHEET_ID_PROD
